export { DepartmentManagement } from './DepartmentManagement';
export { FacultyManagement } from './FacultyManagement';
export { AcademicCourseManagement } from './AcademicCourseManagement';
export { CurriculumEditor } from './CurriculumEditor';
export { LibraryBooksManagement } from './LibraryBooksManagement';
export { AcademicStudentManagement } from './AcademicStudentManagement';
export { default as BulkUploadManager } from './BulkUploadManager';
export { default as MegaCourseUploader } from './MegaCourseUploader';
export { default as ABETCourseGenerator } from './ABETCourseGenerator';
export { default as CourseContentGenerator } from './CourseContentGenerator';
export { default as BulkContentGenerator } from './BulkContentGenerator';
